# DB CONFIGURATION
# DB_HOST = "postgres"
# DB_PORT = '5432'
# DB_NAME = 'dsts'
# DB_USER = 'zamay86'
# DB_PASSWORD = 'matan42'

# LOCAL DB CONFIGURATION
DB_HOST = "localhost"
DB_PORT = '5432'
DB_NAME = 'dsts'
DB_USER = 'dsts'
DB_PASSWORD = '123456'

# PATHS
PATH_JSONS_DIR = "JSONS"
PATH_LINKS_DIR = "LINKS"
PATH_LOGS_DIR = "LOGS"
PATH_REQUEST_FILE = "SEARCH_REQUESTS.txt"

# LOGGER
CURRENT_LOG_FILE = "default"
DEFAULT_FILE_LOG = "default"
FILE_PROGRESS = "progress"
FILE_OUTPUT = "output"
