version: '3'
services:
  scrapper:
    restart: always
    build: .
    network_mode: host
    depends_on:
      - db
  db:
    image : postgres:14
    container_name: db
    expose:
      - "5432"
    environment:
      POSTGRES_DB: "dsts"
      POSTGRES_USER: "dsts"
      POSTGRES_PASSWORD: "123456"
    volumes:
      - ./DB/:/docker-entrypoint-initdb.d
    network_mode: host